spring:
  application:
    name: user-provider
dubbo:
  scan:
    basePackages: com.inspur.service
  application:
    id: user-provider
    name : user-provider
    #心跳检测或转态检查默认的端口 qos
    qos-port: 22222
    qos-enable: true
  ###传输协议层的配置
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    status: server
  registry:
    id: zookeeper
    address: zookeeper://192.168.120.110:2181?backup=192.168.120.150:2181,192.168.120.224:2181,192.168.120.137:2181
